version: "3"

services:
  # The web
  web:
    container_name: web
    build:
      context: "./etc"
      dockerfile: docker-web
    working_dir: /var/www/<mouted-folder>
    volumes:
      - <source-code>:/var/www/<mouted-folder>:delegated
      - ~/.composer/docker-cache/:/root/.composer:cached
    ports:
      - 80:80
    restart: always
    # networks:
    #   docker_network:
    #     ipv4_address: "10.3.0.16"

  # The contab
  crontab:
    container_name: crontab
    build:
      context: "./etc"
      dockerfile: docker-crontab
    volumes:
      - <source-code>:/var/www/<mouted-folder>:delegated
    restart: always

  # The supervisor
  supervisor:
    container_name: supervisor
    build:
      context: "./etc"
      dockerfile: docker-supervisor
    volumes:
      - <source-code>:/var/www/<mouted-folder>:delegated
      - ./etc/conf/supervisor.d:/etc/supervisor/conf.d:delegated
    restart: always

  db:
    container_name: mariadb
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_USER: "<mysql-username>"
      MYSQL_PASSWORD: "mysql-password"
      MYSQL_ROOT_PASSWORD: "mysql-root-password"
    ports:
      - "3306:3306"
    volumes:
      - ./etc/sql:/docker-entrypoint-initdb.d:cached
      - docker_ubuntu_db:/var/lib/mysql
    # networks:
    #   docker_network:
    #     ipv4_address: "10.3.0.14"
# networks:
#   docker_network:
#     driver: "bridge"
#     ipam:
#       config:
#         - subnet: 10.3.0.0/16
volumes:
  docker_ubuntu_db:
